# Use official Node.js image as the base image
FROM node:16

# Set the working directory in the container
WORKDIR /usr/src/app



# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./



# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port the app will run on
EXPOSE 3000

# Command to run the application
CMD ["node", "index.js"]
